### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS23#42]
update R Code in Demo and Slides:

- [x] use base pipe instead of native pipe
- [x] replace strftime with lubridate month, year... 
- [ ] check all slides and demo for outdated R-code
- [x] When updating slides, simulate *change tracking* by duplicating slide and deactivating the old slide
- [ ] in infovis 2 tour d'horizon, make sure all packages are updated and be more explicit if a "package" or "function" is from ggplot2

**Comment by ratnanil** [comment]
no, we can close this
